# version: '3.8'

services:
  postgresdb:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./yellow_taxi_data:/var/lib/postgresql/data"
    restart: always

  pgadmin:                                                                                                                                                                                                                                                                                                                                                
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    # volumes:
    #   - "./pgadmin_data:/var/lib/pgadmin:rw"
    ports:
      - "5050:80"
    